version: "3"
services:
  app:
    build: .
    image: bijoydocker/restful-security
    depends_on:
      - logs
      - mysql
    container_name: app-container
    networks:
      - mynet
    ports:
      - 9090:8080
    env_file:
      - app.env
      #volumes_from:
       # - logs

  mysql:
    image: mysql
    container_name: mysql-container
    networks:
      - mynet
    ports:
      - 3305:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - temp:/tmp

  logs:
    image: bijoydocker/logs-image
    container_name: logs-container
    restart: on-failure


volumes:
  temp:


networks:
  mynet:
    driver: bridge